### ISSUE TITLE
06-mitsuzen-hdi-10-left-arm HW Clamping

### ISSUE THREAD

**Issue by teliot** [Seraphli/EXAPunks#1]
the hardware has a 9999 limit

ADDI #NERV 9949 X
SUBI X 9949 X
SUBI X 9879 X
ADDI 9879 X M

this will clamp #NERV to the range -120, 50

**Comment by Seraphli** [comment]
Thanks! I update the level and the README.md. If you wish to help to update this walkthrough, you can send pull requests. I will do merge ASAP.
