### ISSUE TITLE
DISK_READ_ERROR achievement solution doesn't work

### ISSUE THREAD

**Issue by raspgalax** [Seraphli/EXAPunks#10]
Hi, just to let you know at least on the latest patch, this doesn't work. It just fills up the buffer and stops and doesn't kill the exa

**Comment by Seraphli** [comment]
Thanks for letting me know. Unfortunately, I haven't played this game for a long time. If you are willing to contribute, you can make a pull request. That will be great.

**Comment by raspgalax** [comment]
Okay, I'll try! Thank you for all your work on the guide.
